- name: Create releases directory
  file:
    path: "{{ pushprox_releases_dir }}"
    state: directory

- name: Unpack pushprox
  unarchive:
    src: "{{ pushprox_release_url }}"
    dest: "{{ pushprox_releases_dir }}/"
    remote_src: "{{ pushprox_release_url is search('://') | ternary('yes','no') }}"
    creates: "{{ pushprox_releases_dir }}/PushProx-{{ pushprox_version }}.linux-amd64"
  notify: Restart pushprox client

- name: Create systemd unit directory
  file:
    # TODO: support XDG_CONFIG_HOME if someone actually uses it
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory

- name: Create systemd unit
  template:
    src: pushprox-client.service.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/{{ pushprox_unit_name }}.service"
  notify: Restart pushprox client

- name: Enable loginctl linger
  command:
    cmd: "loginctl enable-linger"
    creates: "/var/lib/systemd/linger/{{ ansible_user_id }}"

- name: Start pushprox-client
  systemd:
    scope: user
    daemon_reload: yes
    name: "{{ pushprox_unit_name }}"
    enabled: yes
    state: started
  register: pushprox_client_start
